# Generated by Django 3.2.13 on 2022-06-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20220626_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestinfo',
            name='Day',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='guestinfo',
            name='Email',
            field=models.EmailField(help_text='Please provide email for confirmation.', max_length=254),
        ),
    ]
